/-
# Excluding near-total odd-primary transversals

A nonempty minimal cyclic-kernel transversal cannot delete every coordinate.
If it leaves exactly one coordinate, its private witnesses force every
translated tuple element into the cyclic subgroup generated by `y`.  The
general finite-abelian lower bound then gives `2^(n-1) <= addOrderOf y`,
contradicting criticality at every genuinely even stratum.  Thus the dyadic
charge failure retains at least two coordinates and only its logarithmic
order-versus-transversal restriction survives.
-/
import MinModulus.G1OddPrimaryDyadicCharge

namespace MinModulus

open Finset

variable {n m : ℕ} {G : Type*} [AddCommGroup G]

/-- A private kernel witness supported on its owner and the unique retained
coordinate makes their pair difference a multiple of the kernel generator. -/
theorem private_kernelWitness_pair_difference_mem_zmultiples
    (g : Fin n → G) (y : G) {B : Finset (Fin n)}
    {b j : Fin n} (hb : b ∈ B) (hj : j ∉ B)
    (hunique : ∀ i : Fin n, i ∉ B → i = j)
    (hprivate : ∃ z : ℤ, ∃ c : Fin n → ℤ,
      z • y ≠ 0 ∧ Witness g (z • y) c ∧ c b ≠ 0 ∧
      ∀ a ∈ B, a ≠ b → c a = 0) :
    g b - g j ∈ AddSubgroup.zmultiples y := by
  classical
  obtain ⟨z, c, hzne, hc, hcb, hzero⟩ := hprivate
  have hbj : b ≠ j := by
    intro heq
    apply hj
    rwa [← heq]
  have hzeroOutside :
      ∀ i : Fin n, i ∉ ({b, j} : Finset (Fin n)) → c i = 0 := by
    intro i hi
    have hib : i ≠ b := by simpa using fun h ↦ hi (by simp [h])
    have hij : i ≠ j := by simpa using fun h ↦ hi (by simp [h])
    have hiB : i ∈ B := by
      by_contra hiNotB
      exact hij (hunique i hiNotB)
    exact hzero i hiB hib
  have hsumPair : c b + c j = 0 := by
    have hrestrict :
        ∑ i ∈ ({b, j} : Finset (Fin n)), c i = ∑ i, c i := by
      exact Finset.sum_subset (by simp) (by
        intro i _ hi
        exact hzeroOutside i hi)
    calc
      c b + c j = ∑ i ∈ ({b, j} : Finset (Fin n)), c i :=
        (Finset.sum_pair (f := c) hbj).symm
      _ = ∑ i, c i := hrestrict
      _ = 0 := hc.2.2.1
  have hvaluePair : c b • g b + c j • g j = z • y := by
    have hrestrict :
        ∑ i ∈ ({b, j} : Finset (Fin n)), c i • g i =
          ∑ i, c i • g i := by
      exact Finset.sum_subset (by simp) (by
        intro i _ hi
        rw [hzeroOutside i hi, zero_zsmul])
    calc
      c b • g b + c j • g j =
          ∑ i ∈ ({b, j} : Finset (Fin n)), c i • g i :=
        (Finset.sum_pair (f := fun i ↦ c i • g i) hbj).symm
      _ = ∑ i, c i • g i := hrestrict
      _ = z • y := hc.2.2.2
  have hcbCases : c b = 1 ∨ c b = -1 := by
    have hgeb := hc.2.1 b
    have hgej := hc.2.1 j
    omega
  rw [AddSubgroup.mem_zmultiples_iff]
  rcases hcbCases with hcbOne | hcbNeg
  · refine ⟨z, ?_⟩
    have hcj : c j = -1 := by omega
    simpa [hcbOne, hcj, sub_eq_add_neg] using hvaluePair.symm
  · refine ⟨-z, ?_⟩
    have hcj : c j = 1 := by omega
    have hneg : -(z • y) = g b - g j := by
      simpa [hcbNeg, hcj, sub_eq_add_neg, add_comm] using
        congrArg Neg.neg hvaluePair.symm
    simpa using hneg

/-- Validity is invariant under translating every tuple entry by the same
group element. -/
theorem validTuple_sub_const
    (g : Fin n → G) (hg : ValidTuple g) (a : G) :
    ValidTuple (fun i ↦ g i - a) := by
  intro k hksum hvalue i
  apply hg k hksum
  have hleft :
      ∑ i, k i • (g i - a) =
        (∑ i, k i • g i) - (∑ i, k i) • a := by
    simp_rw [nsmul_sub]
    rw [Finset.sum_sub_distrib, Finset.sum_nsmul_assoc]
  have hright :
      ∑ i, (g i - a) = (∑ i, g i) - n • a := by
    rw [Finset.sum_sub_distrib, Finset.sum_const,
      Finset.card_univ, Fintype.card_fin]
  rw [hleft, hksum, hright] at hvalue
  exact sub_left_inj.mp hvalue

/-- A nonempty minimal cyclic-kernel transversal omits at least one
coordinate. -/
theorem card_lt_of_nonempty_minimalCyclicKernelSupportTransversal
    (g : Fin n → G) (y : G) {B : Finset (Fin n)}
    (hmin : MinimalCyclicKernelSupportTransversal g y B)
    (hB : B.Nonempty) : B.card < n := by
  classical
  have hle : B.card ≤ n := by simpa using Finset.card_le_univ B
  by_contra hnot
  have hcard : B.card = n := by omega
  have hBuniv : B = Finset.univ := by
    apply Finset.eq_univ_of_card
    simpa using hcard
  obtain ⟨b, hb⟩ := hB
  obtain ⟨z, c, _hzne, hc, hcb, hzero⟩ :=
    exists_private_witness_of_minimalCyclicKernelTransversal
      g y hmin hb
  have hzeroOutside : ∀ i : Fin n, i ≠ b → c i = 0 := by
    intro i hib
    exact hzero i (by rw [hBuniv]; simp) hib
  have hrestrict :
      ∑ i ∈ ({b} : Finset (Fin n)), c i = ∑ i, c i := by
    exact Finset.sum_subset (by simp) (by
      intro i _ hi
      exact hzeroOutside i (by simpa using hi))
  apply hcb
  calc
    c b = ∑ i ∈ ({b} : Finset (Fin n)), c i := by simp
    _ = ∑ i, c i := hrestrict
    _ = 0 := hc.2.2.1

/-- Therefore a nonempty minimal transversal retaining fewer than two
coordinates retains exactly one. -/
theorem one_retained_of_nonempty_minimalTransversal_and_lt_two
    (g : Fin n → G) (y : G) {B : Finset (Fin n)}
    (hmin : MinimalCyclicKernelSupportTransversal g y B)
    (hB : B.Nonempty) (hsmall : n - B.card < 2) :
    n - B.card = 1 := by
  have hlt := card_lt_of_nonempty_minimalCyclicKernelSupportTransversal
    g y hmin hB
  omega

/-- With exactly one retained coordinate, every translated tuple entry lies
in the cyclic kernel subgroup. -/
theorem exists_singletonComplement_all_differences_mem_zmultiples
    (g : Fin n → G) (y : G) {B : Finset (Fin n)}
    (hmin : MinimalCyclicKernelSupportTransversal g y B)
    (hB : B.Nonempty) (hsmall : n - B.card < 2) :
    ∃ j : Fin n, j ∉ B ∧
      ∀ i : Fin n, g i - g j ∈ AddSubgroup.zmultiples y := by
  classical
  have hone := one_retained_of_nonempty_minimalTransversal_and_lt_two
    g y hmin hB hsmall
  have hRcard : (Finset.univ \ B).card = 1 := by
    simpa [Finset.card_sdiff_of_subset (Finset.subset_univ B)] using hone
  obtain ⟨j, hR⟩ := Finset.card_eq_one.mp hRcard
  have hj : j ∉ B := by
    have hjR : j ∈ Finset.univ \ B := by rw [hR]; simp
    exact (Finset.mem_sdiff.mp hjR).2
  have hunique : ∀ i : Fin n, i ∉ B → i = j := by
    intro i hi
    have hiR : i ∈ Finset.univ \ B := Finset.mem_sdiff.mpr ⟨by simp, hi⟩
    rw [hR] at hiR
    simpa using hiR
  refine ⟨j, hj, ?_⟩
  intro i
  by_cases hij : i = j
  · subst i
    simp
  · have hiB : i ∈ B := by
      by_contra hi
      exact hij (hunique i hi)
    exact private_kernelWitness_pair_difference_mem_zmultiples
      g y hiB hj hunique
        (exists_private_witness_of_minimalCyclicKernelTransversal
          g y hmin hiB)

/-- A valid tuple concentrated in one coset of the order-`r` cyclic subgroup
forces `2^(n-1) <= r`. -/
theorem two_pow_pred_le_addOrderOf_of_nearTotal_minimalTransversal
    {m : ℕ} [Fintype G]
    (g : Fin (m + 1) → G) (hg : ValidTuple g) (y : G)
    {B : Finset (Fin (m + 1))}
    (hmin : MinimalCyclicKernelSupportTransversal g y B)
    (hB : B.Nonempty) (hsmall : m + 1 - B.card < 2) :
    2 ^ m ≤ addOrderOf y := by
  obtain ⟨j, _hj, hmem⟩ :=
    exists_singletonComplement_all_differences_mem_zmultiples
      g y hmin hB hsmall
  let gH : Fin (m + 1) → AddSubgroup.zmultiples y :=
    fun i ↦ ⟨g i - g j, hmem i⟩
  have htrans : ValidTuple (fun i ↦ g i - g j) :=
    validTuple_sub_const g hg (g j)
  have hgH : ValidTuple gH := by
    apply validTuple_of_comp (AddSubgroup.zmultiples y).subtype
    simpa [gH] using htrans
  have hcard := card_ge gH hgH
  rw [← Nat.card_eq_fintype_card, Nat.card_zmultiples] at hcard
  exact hcard

/-- Near-total minimal-transversal deletion is impossible in a critical
stratum with a nonzero two-adic factor. -/
theorem not_nearTotal_minimalCyclicKernelTransversal_of_critical_evenStratum
    {m t q ell p : ℕ} [NeZero (2 ^ t * q)]
    (ht : 1 ≤ t)
    (g : Fin (m + 1) → ZMod (2 ^ t * q)) (hg : ValidTuple g)
    (hcritical : 2 ^ t * q < stratumBound (m + 1) t)
    {y : ZMod (2 ^ t * q)}
    (hcert : MersenneTorsionPrimeCertificate q ell p y)
    {B : Finset (Fin (m + 1))}
    (hmin : MinimalCyclicKernelSupportTransversal g y B)
    (hB : B.Nonempty) :
    ¬ (m + 1 - B.card < 2) := by
  intro hsmall
  have hr : 2 ^ m ≤ addOrderOf y :=
    two_pow_pred_le_addOrderOf_of_nearTotal_minimalTransversal
      g hg y hmin hB hsmall
  have hrq : addOrderOf y ≤ q := hcert.torsionOrder_le_oddFactor
  have htwo : 2 ≤ 2 ^ t := by
    simpa using Nat.pow_le_pow_right (by omega : 0 < (2 : ℕ)) ht
  have hcube : 2 ^ (m + 1) ≤ 2 ^ t * q := by
    calc
      2 ^ (m + 1) = 2 * 2 ^ m := by rw [pow_succ]; omega
      _ ≤ 2 * addOrderOf y := Nat.mul_le_mul_left 2 hr
      _ ≤ 2 * q := Nat.mul_le_mul_left 2 hrq
      _ ≤ 2 ^ t * q := Nat.mul_le_mul_right q htwo
  have hbound : stratumBound (m + 1) t ≤ 2 ^ (m + 1) :=
    Nat.sub_le _ _
  omega

/-- The sole numerical failure regime after near-total deletion has been
excluded. -/
def OddPrimaryLogChargeFailureRegime
    (n b t r : ℕ) : Prop :=
  ¬ OddPrimaryStratumCharge n b t r ∧
    2 ≤ n - b ∧
    r < 2 ^ (b + 1) ∧ Nat.log 2 r ≤ b

/-- Lossless minimal-transversal descent with only the logarithmic charge
failure retained. -/
def OddPrimaryMinimalTransversalLogChargeDescent
    {n t q : ℕ} (g : Fin n → ZMod (2 ^ t * q))
    (y : ZMod (2 ^ t * q)) (B : Finset (Fin n)) : Prop :=
  OddPrimaryMinimalTransversalDyadicDescent g y B ∧
    (OddPrimaryRecursiveCounterexample n B.card t q (addOrderOf y) ∨
      (B.Nonempty ∧ OddPrimaryLogChargeFailureRegime
        n B.card t (addOrderOf y)))

/-- Eliminate the near-total arm of the dyadic refinement in every critical
even stratum. -/
theorem oddPrimaryMinimalTransversalLogChargeDescent_of_dyadic
    {m t q ell p : ℕ} [NeZero (2 ^ t * q)]
    (ht : 1 ≤ t)
    (g : Fin (m + 1) → ZMod (2 ^ t * q)) (hg : ValidTuple g)
    (hcritical : 2 ^ t * q < stratumBound (m + 1) t)
    {y : ZMod (2 ^ t * q)}
    (hcert : MersenneTorsionPrimeCertificate q ell p y)
    {B : Finset (Fin (m + 1))}
    (hout : OddPrimaryMinimalTransversalDyadicDescent g y B) :
    OddPrimaryMinimalTransversalLogChargeDescent g y B := by
  refine ⟨hout, ?_⟩
  rcases hout.2 with hrec | ⟨hB, hfail, hsmall | hlog⟩
  · exact Or.inl hrec
  · exfalso
    exact not_nearTotal_minimalCyclicKernelTransversal_of_critical_evenStratum
      ht g hg hcritical hcert hout.1.1 hB hsmall
  · have hnotSmall :=
      not_nearTotal_minimalCyclicKernelTransversal_of_critical_evenStratum
        ht g hg hcritical hcert hout.1.1 hB
    exact Or.inr ⟨hB, hfail, by omega, hlog⟩

/-- Pure-star endpoint with near-total odd-primary deletion removed. -/
def PureEdgeStarLeafOddPrimaryLogChargeOutcome
    {t q : ℕ} (g : Fin (m + 1) → ZMod (2 ^ t * q))
    (h : ZMod (2 ^ t * q)) (r : Fin (m + 1))
    (T : ↥(witnessPureEdgeStarLeaves g h r) →
      ↥(witnessPureEdgeStarLeaves g h r))
    (a : ↥(witnessPureEdgeStarLeaves g h r)) (d : ℕ)
    (center : Fin d → Fin (m + 1)) : Prop :=
  let leaf : Fin d → Fin (m + 1) :=
    fun j ↦ (T^[j.val] a : Fin (m + 1))
  2 * d + 1 ≤ m + 1 ∨
    (d + 2 ≤ m + 1 ∧
      ∃ j k ell : Fin d,
        center j = leaf k ∧ center ell ∉ Set.range leaf) ∨
    (PureEdgeStarLeafRelativeTorsionAlgebra g h r T a d center ∧
      ∃ i : Fin d, ∃ ell p : ℕ, ∃ B : Finset (Fin (m + 1)),
        2 ≤ ell ∧ ell ≤ d ∧
        (2 ^ ell - 1) • (g (leaf i) - (h + g r)) = 0 ∧
        MersenneTorsionPrimeCertificate q ell p
          (g (leaf i) - (h + g r)) ∧
        orderOf (2 : ZMod p) ≤ d ∧
        OddPrimaryMinimalTransversalLogChargeDescent g
          (g (leaf i) - (h + g r)) B)

/-- Refine the dyadic global endpoint to the logarithmic-only residual. -/
theorem pureEdgeStarLeafCycle_logChargeOutcome_of_dyadicChargeOutcome
    {t q : ℕ} [NeZero (2 ^ t * q)]
    (ht : 1 ≤ t)
    (g : Fin (m + 1) → ZMod (2 ^ t * q)) (hg : ValidTuple g)
    (hcritical : 2 ^ t * q < stratumBound (m + 1) t)
    {h : ZMod (2 ^ t * q)} (r : Fin (m + 1))
    (T : ↥(witnessPureEdgeStarLeaves g h r) →
      ↥(witnessPureEdgeStarLeaves g h r))
    {a : ↥(witnessPureEdgeStarLeaves g h r)} {d : ℕ}
    (center : Fin d → Fin (m + 1))
    (hout : PureEdgeStarLeafOddPrimaryDyadicChargeOutcome
      g h r T a d center) :
    PureEdgeStarLeafOddPrimaryLogChargeOutcome
      g h r T a d center := by
  rcases hout with hcap | hmixed |
      ⟨halg, i, ell, p, B, hellTwo, hellD, htorsion, hcert, hordD,
        hdyadic⟩
  · exact Or.inl hcap
  · exact Or.inr (Or.inl hmixed)
  · right
    right
    exact ⟨halg, i, ell, p, B, hellTwo, hellD, htorsion, hcert, hordD,
      oddPrimaryMinimalTransversalLogChargeDescent_of_dyadic
        ht g hg hcritical hcert hdyadic⟩

/-- Global critical even-stratum pure-star endpoint with only the logarithmic
transversal-size obstruction left in its nonrecursive odd-primary branch. -/
theorem exists_minimal_pureEdgeStarLeafCycle_oddPrimaryLogChargeOutcome
    {t q : ℕ} [NeZero (2 ^ t * q)]
    (ht : 1 ≤ t)
    (g : Fin (m + 1) → ZMod (2 ^ t * q)) (hg : ValidTuple g)
    (hcritical : 2 ^ t * q < stratumBound (m + 1) t)
    {h : ZMod (2 ^ t * q)} (hh : h + h = 0) (hne : h ≠ 0)
    (hno : ¬ ∃ z : Fin (m + 1), ∀ c : Fin (m + 1) → ℤ,
      Witness g h c → c z ≠ 0)
    (r : Fin (m + 1))
    (qroot : ReducedSubsetSumCollision g h)
    (hqCanonical : qroot ∈ canonicalReducedCollisions (g := g) hh)
    (hcoeff : subsetCollisionCoeffs qroot.val.1 qroot.val.2 =
        supportAvoidingWitnessAt g hno r ∨
      subsetCollisionCoeffs qroot.val.1 qroot.val.2 =
        -supportAvoidingWitnessAt g hno r)
    (hthree : ¬ WitnessThreeDistinctOmissions g h)
    (hcross : ∀ q' : ReducedSubsetSumCollision g h,
      ¬ ((qroot, q') ∈ canonicalPositiveNegativeCrossPairs (g := g) hh ∨
        (q', qroot) ∈ canonicalPositiveNegativeCrossPairs (g := g) hh))
    (hL : (witnessPureEdgeStarLeaves g h r).Nonempty) :
    ∃ T : ↥(witnessPureEdgeStarLeaves g h r) →
        ↥(witnessPureEdgeStarLeaves g h r),
      ∃ a : ↥(witnessPureEdgeStarLeaves g h r), ∃ d : ℕ,
        ∃ center : Fin d → Fin (m + 1),
          d ≤ (witnessPureEdgeStarLeaves g h r).card ∧
          IsMinimalFixedPointFreeCycle T a d ∧
          Function.Injective center ∧
          (∀ j : Fin d,
            center j ≠ r ∧
            center j ≠ (T^[j.val] a : Fin (m + 1)) ∧
            center j ≠ (T (T^[j.val] a) : Fin (m + 1)) ∧
            (2 : ℤ) • g (center j) =
              h + g r + g (T (T^[j.val] a) : Fin (m + 1))) ∧
          PureEdgeStarLeafOddPrimaryLogChargeOutcome
            g h r T a d center := by
  obtain ⟨T, a, d, center, hdCard, hcycle, hcenter, hcenterSpec, hout⟩ :=
    exists_minimal_pureEdgeStarLeafCycle_oddPrimaryDyadicChargeOutcome
      g hg hcritical hh hne hno r qroot hqCanonical hcoeff hthree hcross hL
  have hout' :=
    pureEdgeStarLeafCycle_logChargeOutcome_of_dyadicChargeOutcome
      ht g hg hcritical r T center hout
  exact ⟨T, a, d, center, hdCard, hcycle, hcenter, hcenterSpec, hout'⟩

end MinModulus
