/-
# The odd-primary subgroup generated by the full saturated leaf cycle

A single relative component gives binomial-layer bounds.  The complete
relative permutation gives more: every translated leaf coordinate has odd
torsion, hence lies in the order-`q` primary subgroup of
`ZMod (2^t*q)`.  The subgroup generated by all `d` leaf displacements is
cyclic.  Choosing its generator `y` and restricting the valid tuple to the
leaf cycle puts a valid `d`-tuple inside `zmultiples y`, so

    2^(d-1) <= addOrderOf y,     addOrderOf y ∣ q.

This is the full exponential cycle-order bound needed to compare the outer
cycle length directly with the size of a failed-charge transversal.
-/
import MinModulus.G1OddPrimaryCycleLayerCharge
import MinModulus.G1SubtupleWitnessKernel
import MinModulus.G1TransportOddProjection

namespace MinModulus

open Finset

variable {n m : ℕ}

/-- The general finite-abelian lower bound indexed directly by tuple length. -/
theorem two_pow_pred_le_card_of_validTuple
    {G : Type*} [AddCommGroup G] [Fintype G]
    (g : Fin n → G) (hg : ValidTuple g) :
    2 ^ (n - 1) ≤ Fintype.card G := by
  cases n with
  | zero => exact Fintype.card_pos_iff.mpr ⟨0⟩
  | succ k => simpa using card_ge g hg

/-- Odd torsion in `ZMod (2^t*q)` lies in the subgroup generated by `2^t`,
the subgroup whose additive order is `q`. -/
theorem oddTorsion_mem_oddPrimary_zmultiples
    {t q M : ℕ} [NeZero (2 ^ t * q)]
    (hM : Odd M) (x : ZMod (2 ^ t * q)) (hx : M • x = 0) :
    x ∈ AddSubgroup.zmultiples
      ((2 ^ t : ℕ) : ZMod (2 ^ t * q)) := by
  letI : NeZero (2 ^ t) := ⟨pow_ne_zero t (by decide)⟩
  have hdiv : 2 ^ t ∣ 2 ^ t * q := dvd_mul_right _ _
  rw [← zmod_castHom_eq_zero_iff_mem_zmultiples hdiv]
  let f : ZMod (2 ^ t * q) →+* ZMod (2 ^ t) :=
    ZMod.castHom hdiv (ZMod (2 ^ t))
  have hmap : M • f x = 0 := by
    calc
      M • f x = f (M • x) := (map_nsmul f M x).symm
      _ = f 0 := by rw [hx]
      _ = 0 := map_zero f
  have hunit : IsUnit (M : ZMod (2 ^ t)) := by
    rw [ZMod.isUnit_iff_coprime]
    exact hM.coprime_two_right.pow_right t
  apply hunit.mul_left_cancel
  simpa [f, nsmul_eq_mul] using hmap

/-- A positive exponent gives an odd Mersenne coefficient. -/
theorem odd_two_pow_sub_one {k : ℕ} (hk : 0 < k) : Odd (2 ^ k - 1) := by
  have hkDecomp : k = (k - 1) + 1 := by omega
  have hpowEq : 2 ^ k = 2 * 2 ^ (k - 1) := by
    calc
      2 ^ k = 2 ^ ((k - 1) + 1) := by rw [← hkDecomp]
      _ = 2 * 2 ^ (k - 1) := by rw [pow_succ, mul_comm]
  refine ⟨2 ^ (k - 1) - 1, ?_⟩
  rw [hpowEq]
  have hpowPos : 1 ≤ 2 ^ (k - 1) := Nat.one_le_two_pow
  omega

/-- Every translated leaf in the saturated two-permutation algebra belongs
to the full order-`q` odd-primary subgroup. -/
theorem PureEdgeStarLeafPermutationAlgebra.allDisplacements_mem_oddPrimary
    {t q : ℕ} [NeZero (2 ^ t * q)]
    (g : Fin (m + 1) → ZMod (2 ^ t * q)) {h : ZMod (2 ^ t * q)}
    (r : Fin (m + 1))
    (T : ↥(witnessPureEdgeStarLeaves g h r) →
      ↥(witnessPureEdgeStarLeaves g h r))
    {a : ↥(witnessPureEdgeStarLeaves g h r)} {d : ℕ}
    (center : Fin d → Fin (m + 1))
    (halg : PureEdgeStarLeafPermutationAlgebra g h r T a d center) :
    ∀ j : Fin d,
      g (T^[j.val] a : Fin (m + 1)) - (h + g r) ∈
        AddSubgroup.zmultiples
          ((2 ^ t : ℕ) : ZMod (2 ^ t * q)) := by
  let leaf : Fin d → Fin (m + 1) :=
    fun j ↦ (T^[j.val] a : Fin (m + 1))
  obtain ⟨P, S, hlocal, _hsum⟩ := halg
  let R : Equiv.Perm (Fin d) := P.symm.trans S
  let y : Fin d → ZMod (2 ^ t * q) :=
    fun j ↦ g (leaf j) - (h + g r)
  have hRrel : ∀ j, (2 : ℤ) • g (leaf j) =
      h + g r + g (leaf (R j)) := by
    intro j
    simpa [R] using (hlocal (P.symm j)).2.2.2.2
  have hy : ∀ j, y (R j) = 2 • y j := by
    intro j
    have hj := hRrel j
    rw [two_zsmul] at hj
    dsimp [y]
    rw [two_nsmul]
    calc
      g (leaf (R j)) - (h + g r) =
          (h + g r + g (leaf (R j))) -
            ((h + g r) + (h + g r)) := by abel
      _ = (g (leaf j) + g (leaf j)) -
            ((h + g r) + (h + g r)) := by rw [← hj]
      _ = (g (leaf j) - (h + g r)) +
            (g (leaf j) - (h + g r)) := by abel
  let D := orderOf R
  have hDpos : 0 < D := orderOf_pos R
  have hRpow : R ^ D = 1 := pow_orderOf_eq_one R
  have hperiod : ∀ j, R^[D] j = j := by
    intro j
    rw [Equiv.Perm.iterate_eq_pow, hRpow]
    rfl
  intro j
  have htorsion : (2 ^ D - 1) • y j = 0 :=
    pow_two_sub_one_nsmul_eq_zero_of_iterate_eq R y hy (hperiod j)
  exact oddTorsion_mem_oddPrimary_zmultiples
    (odd_two_pow_sub_one hDpos) (y j) htorsion

/-- The subgroup generated by all saturated leaf displacements has a
generator whose order divides `q` and is at least `2^(d-1)`. -/
theorem PureEdgeStarLeafPermutationAlgebra.exists_fullCycleOddKernelGenerator
    {t q : ℕ} [NeZero (2 ^ t * q)]
    (g : Fin (m + 1) → ZMod (2 ^ t * q)) (hg : ValidTuple g)
    {h : ZMod (2 ^ t * q)} (r : Fin (m + 1))
    (T : ↥(witnessPureEdgeStarLeaves g h r) →
      ↥(witnessPureEdgeStarLeaves g h r))
    {a : ↥(witnessPureEdgeStarLeaves g h r)} {d : ℕ}
    (hcycle : IsMinimalFixedPointFreeCycle T a d)
    (center : Fin d → Fin (m + 1))
    (halg : PureEdgeStarLeafPermutationAlgebra g h r T a d center) :
    ∃ y : ZMod (2 ^ t * q),
      (∀ j : Fin d,
        g (T^[j.val] a : Fin (m + 1)) - (h + g r) ∈
          AddSubgroup.zmultiples y) ∧
      2 ^ (d - 1) ≤ addOrderOf y ∧
      addOrderOf y ∣ q := by
  let leafFun : Fin d → Fin (m + 1) :=
    fun j ↦ (T^[j.val] a : Fin (m + 1))
  have hleaf : Function.Injective leafFun := by
    intro j k hjk
    apply minimalFixedPointFreeCycle_iterates_injective T hcycle
    exact Subtype.ext hjk
  let leaf : Fin d ↪ Fin (m + 1) := ⟨leafFun, hleaf⟩
  let disp : Fin d → ZMod (2 ^ t * q) :=
    fun j ↦ g (leaf j) - (h + g r)
  let H : AddSubgroup (ZMod (2 ^ t * q)) :=
    AddSubgroup.closure (Set.range disp)
  have hHle : H ≤ AddSubgroup.zmultiples
      ((2 ^ t : ℕ) : ZMod (2 ^ t * q)) := by
    apply (AddSubgroup.closure_le _).mpr
    rintro x ⟨j, rfl⟩
    exact halg.allDisplacements_mem_oddPrimary g r T center j
  letI : IsAddCyclic H := AddSubgroup.isAddCyclic H
  obtain ⟨y, hygen⟩ :=
    (H.isAddCyclic_iff_exists_zmultiples_eq_top).mp (inferInstance : IsAddCyclic H)
  have hmem : ∀ j : Fin d, disp j ∈ AddSubgroup.zmultiples y := by
    intro j
    rw [hygen]
    exact AddSubgroup.subset_closure ⟨j, rfl⟩
  have hsubValid : ValidTuple (fun j ↦ g (leaf j)) :=
    validTuple_embedding leaf g hg
  have htranslated : ValidTuple disp := by
    simpa [disp] using validTuple_sub_const
      (fun j ↦ g (leaf j)) hsubValid (h + g r)
  let gY : Fin d → AddSubgroup.zmultiples y :=
    fun j ↦ ⟨disp j, hmem j⟩
  have hgY : ValidTuple gY := by
    apply validTuple_of_comp (AddSubgroup.zmultiples y).subtype
    simpa [gY] using htranslated
  have hlower : 2 ^ (d - 1) ≤ addOrderOf y := by
    have hcard := two_pow_pred_le_card_of_validTuple gY hgY
    rw [← Nat.card_eq_fintype_card, Nat.card_zmultiples] at hcard
    exact hcard
  have hyH : y ∈ H := by
    rw [← hygen]
    exact AddSubgroup.mem_zmultiples y
  have hyOdd : y ∈ AddSubgroup.zmultiples
      ((2 ^ t : ℕ) : ZMod (2 ^ t * q)) := hHle hyH
  have hdvd := addOrderOf_dvd_of_mem_zmultiples hyOdd
  have hbase : addOrderOf
      ((2 ^ t : ℕ) : ZMod (2 ^ t * q)) = q := by
    rw [ZMod.addOrderOf_coe _ (NeZero.ne (2 ^ t * q))]
    have hgcd : (2 ^ t * q).gcd (2 ^ t) = 2 ^ t :=
      Nat.gcd_eq_right_iff_dvd.mpr (dvd_mul_right _ _)
    rw [hgcd]
    simp [Nat.mul_comm]
  rw [hbase] at hdvd
  exact ⟨y, by simpa [disp, leaf, leafFun] using hmem, hlower, hdvd⟩

/-- Global cycle-layer endpoint enriched, in its saturated branch, by a
generator of the subgroup spanned by every leaf displacement. -/
def PureEdgeStarLeafOddPrimaryFullCycleSubgroupOutcome
    {t q : ℕ} (g : Fin (m + 1) → ZMod (2 ^ t * q))
    (h : ZMod (2 ^ t * q)) (r : Fin (m + 1))
    (T : ↥(witnessPureEdgeStarLeaves g h r) →
      ↥(witnessPureEdgeStarLeaves g h r))
    (a : ↥(witnessPureEdgeStarLeaves g h r)) (d : ℕ)
    (center : Fin d → Fin (m + 1)) : Prop :=
  let leaf : Fin d → Fin (m + 1) :=
    fun j ↦ (T^[j.val] a : Fin (m + 1))
  2 * d + 1 ≤ m + 1 ∨
    (d + 2 ≤ m + 1 ∧
      ∃ j k ell : Fin d,
        center j = leaf k ∧ center ell ∉ Set.range leaf) ∨
    (PureEdgeStarLeafOddPrimaryCycleLayerChargeOutcome
        g h r T a d center ∧
      ∃ y : ZMod (2 ^ t * q),
        (∀ j : Fin d,
          g (leaf j) - (h + g r) ∈ AddSubgroup.zmultiples y) ∧
        2 ^ (d - 1) ≤ addOrderOf y ∧
        addOrderOf y ∣ q)

/-- Attach the full-cycle odd-primary generator without discarding the least
component, quotient descent, private witnesses, or log-charge data. -/
theorem pureEdgeStarLeafCycle_fullCycleSubgroupOutcome_of_cycleLayerChargeOutcome
    {t q : ℕ} [NeZero (2 ^ t * q)]
    (g : Fin (m + 1) → ZMod (2 ^ t * q)) (hg : ValidTuple g)
    {h : ZMod (2 ^ t * q)} (r : Fin (m + 1))
    (T : ↥(witnessPureEdgeStarLeaves g h r) →
      ↥(witnessPureEdgeStarLeaves g h r))
    {a : ↥(witnessPureEdgeStarLeaves g h r)} {d : ℕ}
    (hcycle : IsMinimalFixedPointFreeCycle T a d)
    (center : Fin d → Fin (m + 1))
    (hout : PureEdgeStarLeafOddPrimaryCycleLayerChargeOutcome
      g h r T a d center) :
    PureEdgeStarLeafOddPrimaryFullCycleSubgroupOutcome
      g h r T a d center := by
  have hout' := hout
  rcases hout with hcap | hmixed |
      ⟨hrelative, _hlayer, _i, _ell, _p, _B, _hellTwo, _hellD, _hodd,
        _htorsion, _hlayers, _hcert, _hordD, _hlog⟩
  · exact Or.inl hcap
  · exact Or.inr (Or.inl hmixed)
  · right
    right
    have hperm := hrelative.permutationAlgebra g r T center
    obtain ⟨y, hmem, hlower, hdvd⟩ :=
      hperm.exists_fullCycleOddKernelGenerator g hg r T hcycle center
    exact ⟨hout', y, hmem, hlower, hdvd⟩

/-- Global critical even-stratum endpoint carrying both the least-component
binomial bounds and the full-cycle exponential odd-subgroup generator. -/
theorem exists_minimal_pureEdgeStarLeafCycle_oddPrimaryFullCycleSubgroupOutcome
    {t q : ℕ} [NeZero (2 ^ t * q)]
    (ht : 1 ≤ t)
    (g : Fin (m + 1) → ZMod (2 ^ t * q)) (hg : ValidTuple g)
    (hcritical : 2 ^ t * q < stratumBound (m + 1) t)
    {h : ZMod (2 ^ t * q)} (hh : h + h = 0) (hne : h ≠ 0)
    (hno : ¬ ∃ z : Fin (m + 1), ∀ c : Fin (m + 1) → ℤ,
      Witness g h c → c z ≠ 0)
    (r : Fin (m + 1))
    (qroot : ReducedSubsetSumCollision g h)
    (hqCanonical : qroot ∈ canonicalReducedCollisions (g := g) hh)
    (hcoeff : subsetCollisionCoeffs qroot.val.1 qroot.val.2 =
        supportAvoidingWitnessAt g hno r ∨
      subsetCollisionCoeffs qroot.val.1 qroot.val.2 =
        -supportAvoidingWitnessAt g hno r)
    (hthree : ¬ WitnessThreeDistinctOmissions g h)
    (hcross : ∀ q' : ReducedSubsetSumCollision g h,
      ¬ ((qroot, q') ∈ canonicalPositiveNegativeCrossPairs (g := g) hh ∨
        (q', qroot) ∈ canonicalPositiveNegativeCrossPairs (g := g) hh))
    (hL : (witnessPureEdgeStarLeaves g h r).Nonempty) :
    ∃ T : ↥(witnessPureEdgeStarLeaves g h r) →
        ↥(witnessPureEdgeStarLeaves g h r),
      ∃ a : ↥(witnessPureEdgeStarLeaves g h r), ∃ d : ℕ,
        ∃ center : Fin d → Fin (m + 1),
          d ≤ (witnessPureEdgeStarLeaves g h r).card ∧
          IsMinimalFixedPointFreeCycle T a d ∧
          Function.Injective center ∧
          (∀ j : Fin d,
            center j ≠ r ∧
            center j ≠ (T^[j.val] a : Fin (m + 1)) ∧
            center j ≠ (T (T^[j.val] a) : Fin (m + 1)) ∧
            (2 : ℤ) • g (center j) =
              h + g r + g (T (T^[j.val] a) : Fin (m + 1))) ∧
          PureEdgeStarLeafOddPrimaryFullCycleSubgroupOutcome
            g h r T a d center := by
  obtain ⟨T, a, d, center, hdCard, hcycle, hcenter, hcenterSpec, hout⟩ :=
    exists_minimal_pureEdgeStarLeafCycle_oddPrimaryCycleLayerChargeOutcome
      ht g hg hcritical hh hne hno r qroot hqCanonical hcoeff hthree hcross hL
  have hout' :=
    pureEdgeStarLeafCycle_fullCycleSubgroupOutcome_of_cycleLayerChargeOutcome
      g hg r T hcycle center hout
  exact ⟨T, a, d, center, hdCard, hcycle, hcenter, hcenterSpec, hout'⟩

end MinModulus
