/-
# Incidence of the full-cycle odd-primary transversal

Every pair of distinct cycle-leaf coordinates has a nonzero difference in
the cyclic subgroup generated by `y_full`.  The two-point coefficient vector
is therefore a nonzero kernel-layer witness.  A cyclic-kernel support
transversal must hit every such pair, so it contains all but at most one
cycle leaf.  In particular

    d - 1 <= |B_full ∩ leafRange|.

This strengthens the numerical charge-failure bound `d-1 <= |B_full|` to an
actual incidence statement, and it holds in both the recursive and failed
charge arms.
-/
import MinModulus.G1OddPrimaryFullCycleCharge

namespace MinModulus

open Finset

variable {n m : ℕ} {G : Type*} [AddCommGroup G]

/-- A cyclic-kernel transversal hits the two coordinates of every nonzero
pair difference lying in the generated cyclic subgroup. -/
theorem mem_left_or_mem_right_of_pairDifference_mem_zmultiples
    (g : Fin n → G) (hg : ValidTuple g) (y : G)
    {B : Finset (Fin n)}
    (hB : CyclicKernelSupportTransversal g y B)
    {a b : Fin n} (hab : a ≠ b)
    (hdiff : g a - g b ∈ AddSubgroup.zmultiples y) :
    a ∈ B ∨ b ∈ B := by
  rw [AddSubgroup.mem_zmultiples_iff] at hdiff
  obtain ⟨z, hz⟩ := hdiff
  let c : Fin n → ℤ :=
    fun i => (if i = a then 1 else 0) - (if i = b then 1 else 0)
  have hca : c a = 1 := by simp [c, hab]
  have hcb : c b = -1 := by simp [c, Ne.symm hab]
  have hcPair : Witness g (g a - g b) c := by
    refine ⟨?_, ?_, ?_, ?_⟩
    · intro hc
      have hzero := congrFun hc a
      rw [hca, Pi.zero_apply] at hzero
      omega
    · intro i
      by_cases hia : i = a
      · subst i
        rw [hca]
        omega
      by_cases hib : i = b
      · subst i
        rw [hcb]
      · simp [c, hia, hib]
    · rw [show (∑ i, c i) =
          (∑ i, if i = a then (1 : ℤ) else 0) -
            ∑ i, if i = b then (1 : ℤ) else 0 by
        rw [Finset.sum_sub_distrib]]
      rw [Finset.sum_ite_eq' univ a fun _ => (1 : ℤ),
        Finset.sum_ite_eq' univ b fun _ => (1 : ℤ)]
      simp
    · have hterm : ∀ i, c i • g i =
          (if i = a then g i else 0) -
            (if i = b then g i else 0) := by
        intro i
        simp only [c, sub_smul, ite_smul, one_smul, zero_smul]
      rw [Finset.sum_congr rfl fun i _ => hterm i,
        Finset.sum_sub_distrib,
        Finset.sum_ite_eq' univ a g,
        Finset.sum_ite_eq' univ b g]
      simp
  have htarget : z • y ≠ 0 := by
    rw [hz]
    exact sub_ne_zero.mpr ((validTuple_injective g hg).ne hab)
  have hc : Witness g (z • y) c := by
    rwa [hz]
  obtain ⟨i, hiB, hci⟩ := hB z htarget c hc
  by_cases hia : i = a
  · exact Or.inl (by simpa [hia] using hiB)
  by_cases hib : i = b
  · exact Or.inr (by simpa [hib] using hiB)
  · simp [c, hia, hib] at hci

/-- If all members of an injectively indexed coordinate family lie in one
coset of `zmultiples y`, at most one family member can be omitted by a
cyclic-kernel support transversal. -/
theorem card_cycleRange_sdiff_cyclicKernelTransversal_le_one
    (g : Fin n → G) (hg : ValidTuple g) (y : G)
    {B : Finset (Fin n)}
    (hB : CyclicKernelSupportTransversal g y B)
    {d : ℕ} (leaf : Fin d → Fin n)
    (base : G)
    (hmem : ∀ j : Fin d,
      g (leaf j) - base ∈ AddSubgroup.zmultiples y) :
    ((Finset.univ.image leaf) \ B).card ≤ 1 := by
  rw [Finset.card_le_one]
  intro x hx y' hy'
  have hxRange := (Finset.mem_sdiff.mp hx).1
  have hxNotB := (Finset.mem_sdiff.mp hx).2
  have hyRange := (Finset.mem_sdiff.mp hy').1
  have hyNotB := (Finset.mem_sdiff.mp hy').2
  obtain ⟨j, _hj, rfl⟩ := Finset.mem_image.mp hxRange
  obtain ⟨k, _hk, rfl⟩ := Finset.mem_image.mp hyRange
  by_contra hjk
  have hdiff : g (leaf j) - g (leaf k) ∈
      AddSubgroup.zmultiples y := by
    have hsub := (AddSubgroup.zmultiples y).sub_mem (hmem j) (hmem k)
    have heq :
        (g (leaf j) - base) - (g (leaf k) - base) =
          g (leaf j) - g (leaf k) := by
      abel
    rwa [heq] at hsub
  rcases mem_left_or_mem_right_of_pairDifference_mem_zmultiples
      g hg y hB hjk hdiff with hjB | hkB
  · exact hxNotB hjB
  · exact hyNotB hkB

/-- Consequently the transversal contains at least `d-1` members of the
indexed cycle range itself. -/
theorem pred_le_card_cyclicKernelTransversal_inter_cycleRange
    (g : Fin n → G) (hg : ValidTuple g) (y : G)
    {B : Finset (Fin n)}
    (hB : CyclicKernelSupportTransversal g y B)
    {d : ℕ} (leaf : Fin d → Fin n) (hleaf : Function.Injective leaf)
    (base : G)
    (hmem : ∀ j : Fin d,
      g (leaf j) - base ∈ AddSubgroup.zmultiples y) :
    d - 1 ≤ (B ∩ Finset.univ.image leaf).card := by
  let L : Finset (Fin n) := Finset.univ.image leaf
  have hmiss : (L \ B).card ≤ 1 := by
    simpa [L] using
      card_cycleRange_sdiff_cyclicKernelTransversal_le_one
        g hg y hB leaf base hmem
  have hLcard : L.card = d := by
    simp [L, Finset.card_image_of_injective _ hleaf]
  have hpartition := Finset.card_sdiff_add_card_inter L B
  have hinter : (L ∩ B).card = (B ∩ L).card := by
    rw [Finset.inter_comm]
  change d - 1 ≤ (B ∩ L).card
  omega

/-- The full-cycle charge descent with the all-but-one leaf-incidence theorem
attached around the same generator and transversal. -/
def OddPrimaryFullCycleIncidenceChargeDescent
    {t q : ℕ} (g : Fin (m + 1) → ZMod (2 ^ t * q))
    (y : ZMod (2 ^ t * q)) (B : Finset (Fin (m + 1)))
    (d : ℕ) (leaf : Fin d → Fin (m + 1)) : Prop :=
  OddPrimaryFullCycleMinimalTransversalChargeDescent g y B d ∧
    ((Finset.univ.image leaf) \ B).card ≤ 1 ∧
    d - 1 ≤ (B ∩ Finset.univ.image leaf).card

/-- Install the all-but-one incidence conclusion on any full-cycle charge
descent whose same generator contains every translated leaf. -/
theorem fullCycleIncidenceChargeDescent_of_chargeDescent
    {t q d : ℕ} [NeZero (2 ^ t * q)]
    (g : Fin (m + 1) → ZMod (2 ^ t * q)) (hg : ValidTuple g)
    {h : ZMod (2 ^ t * q)} (r : Fin (m + 1))
    (T : ↥(witnessPureEdgeStarLeaves g h r) →
      ↥(witnessPureEdgeStarLeaves g h r))
    {a : ↥(witnessPureEdgeStarLeaves g h r)}
    (hcycle : IsMinimalFixedPointFreeCycle T a d)
    {y : ZMod (2 ^ t * q)} {B : Finset (Fin (m + 1))}
    (hmem : ∀ j : Fin d,
      g (T^[j.val] a : Fin (m + 1)) - (h + g r) ∈
        AddSubgroup.zmultiples y)
    (hdescent : OddPrimaryFullCycleMinimalTransversalChargeDescent
      g y B d) :
    OddPrimaryFullCycleIncidenceChargeDescent g y B d
      (fun j ↦ (T^[j.val] a : Fin (m + 1))) := by
  let leaf : Fin d → Fin (m + 1) :=
    fun j ↦ (T^[j.val] a : Fin (m + 1))
  have hleaf : Function.Injective leaf := by
    intro j k hjk
    apply minimalFixedPointFreeCycle_iterates_injective T hcycle
    exact Subtype.ext hjk
  have hmiss :=
    card_cycleRange_sdiff_cyclicKernelTransversal_le_one
      g hg y hdescent.1.1 leaf (h + g r) hmem
  have hinter :=
    pred_le_card_cyclicKernelTransversal_inter_cycleRange
      g hg y hdescent.1.1 leaf hleaf (h + g r) hmem
  exact ⟨hdescent, by simpa [leaf] using hmiss,
    by simpa [leaf] using hinter⟩

/-- Global endpoint retaining the full charge package and showing that its
minimal transversal contains all but at most one displayed cycle leaf. -/
def PureEdgeStarLeafOddPrimaryFullCycleIncidenceOutcome
    {t q : ℕ} (g : Fin (m + 1) → ZMod (2 ^ t * q))
    (h : ZMod (2 ^ t * q)) (r : Fin (m + 1))
    (T : ↥(witnessPureEdgeStarLeaves g h r) →
      ↥(witnessPureEdgeStarLeaves g h r))
    (a : ↥(witnessPureEdgeStarLeaves g h r)) (d : ℕ)
    (center : Fin d → Fin (m + 1)) : Prop :=
  let leaf : Fin d → Fin (m + 1) :=
    fun j ↦ (T^[j.val] a : Fin (m + 1))
  2 * d + 1 ≤ m + 1 ∨
    (d + 2 ≤ m + 1 ∧
      ∃ j k ell : Fin d,
        center j = leaf k ∧ center ell ∉ Set.range leaf) ∨
    (PureEdgeStarLeafOddPrimaryFullCycleChargeOutcome
        g h r T a d center ∧
      ∃ y : ZMod (2 ^ t * q), ∃ B : Finset (Fin (m + 1)),
        (∀ j : Fin d,
          g (leaf j) - (h + g r) ∈ AddSubgroup.zmultiples y) ∧
        OddPrimaryFullCycleIncidenceChargeDescent g y B d leaf)

/-- Refine the full-cycle charge endpoint by the leaf-incidence theorem. -/
theorem pureEdgeStarLeafCycle_fullCycleIncidenceOutcome_of_fullCycleChargeOutcome
    {t q : ℕ} [NeZero (2 ^ t * q)]
    (g : Fin (m + 1) → ZMod (2 ^ t * q)) (hg : ValidTuple g)
    {h : ZMod (2 ^ t * q)} (r : Fin (m + 1))
    (T : ↥(witnessPureEdgeStarLeaves g h r) →
      ↥(witnessPureEdgeStarLeaves g h r))
    {a : ↥(witnessPureEdgeStarLeaves g h r)} {d : ℕ}
    (hcycle : IsMinimalFixedPointFreeCycle T a d)
    (center : Fin d → Fin (m + 1))
    (hout : PureEdgeStarLeafOddPrimaryFullCycleChargeOutcome
      g h r T a d center) :
    PureEdgeStarLeafOddPrimaryFullCycleIncidenceOutcome
      g h r T a d center := by
  have hout' := hout
  rcases hout with hcap | hmixed |
      ⟨_hsubgroup, y, B, hmem, hdescent⟩
  · exact Or.inl hcap
  · exact Or.inr (Or.inl hmixed)
  · right
    right
    exact ⟨hout', y, B, hmem,
      fullCycleIncidenceChargeDescent_of_chargeDescent
        g hg r T hcycle hmem hdescent⟩

/-- Global critical even-stratum endpoint with all-but-one cycle-leaf
incidence attached to the full odd-primary transversal. -/
theorem exists_minimal_pureEdgeStarLeafCycle_oddPrimaryFullCycleIncidenceOutcome
    {t q : ℕ} [NeZero (2 ^ t * q)]
    (ht : 1 ≤ t)
    (g : Fin (m + 1) → ZMod (2 ^ t * q)) (hg : ValidTuple g)
    (hcritical : 2 ^ t * q < stratumBound (m + 1) t)
    {h : ZMod (2 ^ t * q)} (hh : h + h = 0) (hne : h ≠ 0)
    (hno : ¬ ∃ z : Fin (m + 1), ∀ c : Fin (m + 1) → ℤ,
      Witness g h c → c z ≠ 0)
    (r : Fin (m + 1))
    (qroot : ReducedSubsetSumCollision g h)
    (hqCanonical : qroot ∈ canonicalReducedCollisions (g := g) hh)
    (hcoeff : subsetCollisionCoeffs qroot.val.1 qroot.val.2 =
        supportAvoidingWitnessAt g hno r ∨
      subsetCollisionCoeffs qroot.val.1 qroot.val.2 =
        -supportAvoidingWitnessAt g hno r)
    (hthree : ¬ WitnessThreeDistinctOmissions g h)
    (hcross : ∀ q' : ReducedSubsetSumCollision g h,
      ¬ ((qroot, q') ∈ canonicalPositiveNegativeCrossPairs (g := g) hh ∨
        (q', qroot) ∈ canonicalPositiveNegativeCrossPairs (g := g) hh))
    (hL : (witnessPureEdgeStarLeaves g h r).Nonempty) :
    ∃ T : ↥(witnessPureEdgeStarLeaves g h r) →
        ↥(witnessPureEdgeStarLeaves g h r),
      ∃ a : ↥(witnessPureEdgeStarLeaves g h r), ∃ d : ℕ,
        ∃ center : Fin d → Fin (m + 1),
          d ≤ (witnessPureEdgeStarLeaves g h r).card ∧
          IsMinimalFixedPointFreeCycle T a d ∧
          Function.Injective center ∧
          (∀ j : Fin d,
            center j ≠ r ∧
            center j ≠ (T^[j.val] a : Fin (m + 1)) ∧
            center j ≠ (T (T^[j.val] a) : Fin (m + 1)) ∧
            (2 : ℤ) • g (center j) =
              h + g r + g (T (T^[j.val] a) : Fin (m + 1))) ∧
          PureEdgeStarLeafOddPrimaryFullCycleIncidenceOutcome
            g h r T a d center := by
  obtain ⟨T, a, d, center, hdCard, hcycle, hcenter, hcenterSpec, hout⟩ :=
    exists_minimal_pureEdgeStarLeafCycle_oddPrimaryFullCycleChargeOutcome
      ht g hg hcritical hh hne hno r qroot hqCanonical hcoeff hthree hcross hL
  have hout' :=
    pureEdgeStarLeafCycle_fullCycleIncidenceOutcome_of_fullCycleChargeOutcome
      g hg r T hcycle center hout
  exact ⟨T, a, d, center, hdCard, hcycle, hcenter, hcenterSpec, hout'⟩

end MinModulus
