/-
# Exact witness kernel under halving

Coordinatewise reduction modulo half the cyclic modulus need not preserve
validity.  This file identifies the obstruction exactly.  More generally, if
an additive homomorphism has kernel generated by an involution `h`, then for a
valid tuple its zero witnesses after mapping are precisely its witnesses at
`h` before mapping.
-/
import MinModulus.G1AvoidanceZeroZeroTwoQuarter

namespace MinModulus

open Finset

variable {m : ℕ} {G H : Type*} [AddCommGroup G] [AddCommGroup H]

/-- Every integer multiple of an involution is either zero or the involution
itself. -/
theorem zsmul_involution_eq_zero_or_self {h : G}
    (hh : h + h = 0) (a : ℤ) : a • h = 0 ∨ a • h = h := by
  rcases Int.even_or_odd a with ⟨b, hb⟩ | ⟨b, hb⟩
  · left
    subst hb
    rw [add_smul, ← smul_add, hh, smul_zero]
  · right
    subst hb
    rw [add_smul, one_smul, mul_comm 2 b, mul_smul, two_zsmul, hh,
      smul_zero, zero_add]

/-- Exact kernel principle for witnesses.  If `ker f = ⟨h⟩` and `h` is an
involution, validity rules out the zero lift of a downstairs zero witness, so
its lift has value exactly `h`. -/
theorem zeroWitness_map_iff_halfWitness_of_ker_eq_zmultiples
    (f : G →+ H) (g : Fin m → G) (hg : ValidTuple g) {h : G}
    (hh : h + h = 0)
    (hker : f.ker = AddSubgroup.zmultiples h)
    (c : Fin m → ℤ) :
    Witness (fun i ↦ f (g i)) 0 c ↔ Witness g h c := by
  constructor
  · rintro hc
    have hmem : (∑ i, c i • g i) ∈ f.ker := by
      rw [AddMonoidHom.mem_ker, map_sum]
      rw [Finset.sum_congr rfl fun i _ ↦ map_zsmul f (c i) (g i)]
      exact hc.2.2.2
    rw [hker, AddSubgroup.mem_zmultiples_iff] at hmem
    obtain ⟨a, ha⟩ := hmem
    rcases zsmul_involution_eq_zero_or_self hh a with hzero | hhalf
    · exact False.elim ((validTuple_iff_no_zero_witness g).mp hg c
        ⟨hc.1, hc.2.1, hc.2.2.1, by rw [← ha, hzero]⟩)
    · exact ⟨hc.1, hc.2.1, hc.2.2.1, by rw [← ha, hhalf]⟩
  · intro hc
    have hfh : f h = 0 := by
      rw [← AddMonoidHom.mem_ker, hker, AddSubgroup.mem_zmultiples_iff]
      exact ⟨1, one_zsmul h⟩
    have hc' := witness_map_addMonoidHom f g hc
    rw [hfh] at hc'
    exact hc'

/-- The kernel of cyclic reduction `ZMod N → ZMod M` is generated by the
class of `M`. -/
theorem zmodCastHom_ker_eq_zmultiples
    {N M : ℕ} [NeZero N] [NeZero M] (hdvd : M ∣ N) :
    (ZMod.castHom hdvd (ZMod M)).toAddMonoidHom.ker =
      AddSubgroup.zmultiples ((M : ℕ) : ZMod N) := by
  apply le_antisymm
  · intro x hx
    rw [AddMonoidHom.mem_ker] at hx
    have hx0 : ZMod.castHom hdvd (ZMod M) x = 0 := hx
    rw [ZMod.castHom_apply, ← ZMod.natCast_val,
      ZMod.natCast_eq_zero_iff] at hx0
    obtain ⟨q, hq⟩ := hx0
    rw [AddSubgroup.mem_zmultiples_iff]
    refine ⟨(q : ℤ), ?_⟩
    have hmul : (q : ZMod N) * ((M : ℕ) : ZMod N) =
        ((M * q : ℕ) : ZMod N) := by
      push_cast
      ring
    rw [natCast_zsmul, nsmul_eq_mul, hmul, ← hq,
      ZMod.natCast_zmod_val]
  · rw [AddSubgroup.zmultiples_le, AddMonoidHom.mem_ker]
    show ZMod.castHom hdvd (ZMod M) ((M : ℕ) : ZMod N) = 0
    rw [map_natCast, ZMod.natCast_self]

/-- Cyclic specialization: for a valid tuple modulo `N=2M`, the zero
witnesses after coordinatewise reduction modulo `M` are exactly the original
half witnesses. -/
theorem zmodCast_zeroWitness_iff_halfWitness
    {N M : ℕ} [NeZero N] (hN : N = 2 * M)
    (g : Fin m → ZMod N) (hg : ValidTuple g) (c : Fin m → ℤ) :
    let f : ZMod N →+* ZMod M :=
      ZMod.castHom (show M ∣ N by exact ⟨2, by omega⟩) (ZMod M)
    Witness (fun i ↦ f (g i)) 0 c ↔ Witness g (M : ZMod N) c := by
  have hM : 0 < M := by
    have hNpos : 0 < N := Nat.pos_of_ne_zero (NeZero.ne N)
    omega
  letI : NeZero M := ⟨Nat.ne_of_gt hM⟩
  let hdvd : M ∣ N := ⟨2, by omega⟩
  let f : ZMod N →+* ZMod M := ZMod.castHom hdvd (ZMod M)
  dsimp only
  exact zeroWitness_map_iff_halfWitness_of_ker_eq_zmultiples
    f.toAddMonoidHom g hg (half_add_half hN)
      (zmodCastHom_ker_eq_zmultiples hdvd) c

/-- Consequently, coordinatewise halving preserves validity exactly when the
original tuple has no half witness. -/
theorem validTuple_zmodCast_iff_no_halfWitness
    {N M : ℕ} [NeZero N] (hN : N = 2 * M)
    (g : Fin m → ZMod N) (hg : ValidTuple g) :
    let f : ZMod N →+* ZMod M :=
      ZMod.castHom (show M ∣ N by exact ⟨2, by omega⟩) (ZMod M)
    ValidTuple (fun i ↦ f (g i)) ↔
      ∀ c : Fin m → ℤ, ¬ Witness g (M : ZMod N) c := by
  let f : ZMod N →+* ZMod M :=
    ZMod.castHom (show M ∣ N by exact ⟨2, by omega⟩) (ZMod M)
  dsimp only
  rw [validTuple_iff_no_zero_witness]
  constructor
  · intro hvalid c hc
    exact hvalid c ((zmodCast_zeroWitness_iff_halfWitness hN g hg c).2 hc)
  · intro hno c hc
    exact hno c ((zmodCast_zeroWitness_iff_halfWitness hN g hg c).1 hc)

end MinModulus
