import MinModulus.RLiftDispatch

/-!
# Small-k certificates at L = 2 (k = 4)

Generated by `gen_smallk.py`.
-/

namespace MinModulus

set_option maxHeartbeats 1600000 in
theorem rliftSmallK2_e0_not_valid (e : ℕ) (he : e % 14 = 0)
    {g β : Fin (2 + 3) → ZMod (2 ^ (2 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 2)
    (hg : ∀ i, g i = ((rliftParentE 2 e i : ℕ) :
        ZMod (2 ^ (2 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 14
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 2 e 0 (e / 14)
    (by rw [show (2 * (2 ^ (2 + 1) - 1) : ℕ) = 14 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, 3, -1, -1] : Fin (2 + 3) → ℤ)
    (![-1, 2, -1, 1, -1] : Fin (2 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (2 + 3))) (by decide) (by decide)
    (by decide)
    ⟨1, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK2_e1_not_valid (e : ℕ) (he : e % 14 = 1)
    {g β : Fin (2 + 3) → ZMod (2 ^ (2 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 2)
    (hg : ∀ i, g i = ((rliftParentE 2 e i : ℕ) :
        ZMod (2 ^ (2 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 14
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 2 e 1 (e / 14)
    (by rw [show (2 * (2 ^ (2 + 1) - 1) : ℕ) = 14 from by norm_num]; omega)
    hβ hg
  have hsh : rliftParentSheet 2 = rliftParentE 2 1 := rfl
  rw [← hsh] at hg'
  exact rliftParentSheet_not_valid (by norm_num) (by decide) hβ' hg'

set_option maxHeartbeats 1600000 in
theorem rliftSmallK2_e2_not_valid (e : ℕ) (he : e % 14 = 2)
    {g β : Fin (2 + 3) → ZMod (2 ^ (2 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 2)
    (hg : ∀ i, g i = ((rliftParentE 2 e i : ℕ) :
        ZMod (2 ^ (2 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 14
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 2 e 2 (e / 14)
    (by rw [show (2 * (2 ^ (2 + 1) - 1) : ℕ) = 14 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_triple_contra hβ' hg' hv
    (![-1, 0, -1, 1, 1] : Fin (2 + 3) → ℤ)
    (![-1, 0, 0, -1, 2] : Fin (2 + 3) → ℤ)
    (![0, 0, -1, 2, -1] : Fin (2 + 3) → ℤ)
    (by decide) (by decide) (by decide)
    (by decide) (by decide) (by decide)
    (j₁ := (⟨0, by decide⟩ : Fin (2 + 3)))
    (j₂ := (⟨0, by decide⟩ : Fin (2 + 3)))
    (j₃ := (⟨2, by decide⟩ : Fin (2 + 3)))
    (by decide) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ ⟨0, by decide⟩ ⟨0, by decide⟩
    ⟨0, by decide⟩

set_option maxHeartbeats 1600000 in
theorem rliftSmallK2_e3_not_valid (e : ℕ) (he : e % 14 = 3)
    {g β : Fin (2 + 3) → ZMod (2 ^ (2 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 2)
    (hg : ∀ i, g i = ((rliftParentE 2 e i : ℕ) :
        ZMod (2 ^ (2 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 14
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 2 e 3 (e / 14)
    (by rw [show (2 * (2 ^ (2 + 1) - 1) : ℕ) = 14 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, -1, 3, 0, -1] : Fin (2 + 3) → ℤ)
    (![-1, 1, -1, 2, -1] : Fin (2 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (2 + 3))) (by decide) (by decide)
    (by decide)
    ⟨1, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK2_e4_not_valid (e : ℕ) (he : e % 14 = 4)
    {g β : Fin (2 + 3) → ZMod (2 ^ (2 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 2)
    (hg : ∀ i, g i = ((rliftParentE 2 e i : ℕ) :
        ZMod (2 ^ (2 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 14
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 2 e 4 (e / 14)
    (by rw [show (2 * (2 ^ (2 + 1) - 1) : ℕ) = 14 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 2, 1, -1, -1] : Fin (2 + 3) → ℤ)
    (![3, 0, -1, -1, -1] : Fin (2 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (2 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK2_e5_not_valid (e : ℕ) (he : e % 14 = 5)
    {g β : Fin (2 + 3) → ZMod (2 ^ (2 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 2)
    (hg : ∀ i, g i = ((rliftParentE 2 e i : ℕ) :
        ZMod (2 ^ (2 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 14
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 2 e 5 (e / 14)
    (by rw [show (2 * (2 ^ (2 + 1) - 1) : ℕ) = 14 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, -1, 4, -1, -1] : Fin (2 + 3) → ℤ)
    (![-1, 1, 0, 1, -1] : Fin (2 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (2 + 3))) (by decide) (by decide)
    (by decide)
    ⟨1, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK2_e6_not_valid (e : ℕ) (he : e % 14 = 6)
    {g β : Fin (2 + 3) → ZMod (2 ^ (2 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 2)
    (hg : ∀ i, g i = ((rliftParentE 2 e i : ℕ) :
        ZMod (2 ^ (2 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 14
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 2 e 6 (e / 14)
    (by rw [show (2 * (2 ^ (2 + 1) - 1) : ℕ) = 14 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, -1, 3, -1] : Fin (2 + 3) → ℤ)
    (![1, 2, -1, -1, -1] : Fin (2 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (2 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK2_e7_not_valid (e : ℕ) (he : e % 14 = 7)
    {g β : Fin (2 + 3) → ZMod (2 ^ (2 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 2)
    (hg : ∀ i, g i = ((rliftParentE 2 e i : ℕ) :
        ZMod (2 ^ (2 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 14
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 2 e 7 (e / 14)
    (by rw [show (2 * (2 ^ (2 + 1) - 1) : ℕ) = 14 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 1, 1, 0, -1] : Fin (2 + 3) → ℤ)
    (![3, -1, -1, 0, -1] : Fin (2 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (2 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK2_e8_not_valid (e : ℕ) (he : e % 14 = 8)
    {g β : Fin (2 + 3) → ZMod (2 ^ (2 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 2)
    (hg : ∀ i, g i = ((rliftParentE 2 e i : ℕ) :
        ZMod (2 ^ (2 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 14
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 2 e 8 (e / 14)
    (by rw [show (2 * (2 ^ (2 + 1) - 1) : ℕ) = 14 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 4, -1, -1, -1] : Fin (2 + 3) → ℤ)
    (![-1, 2, -1, -1, 1] : Fin (2 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (2 + 3))) (by decide) (by decide)
    (by decide)
    ⟨-1, by decide⟩ (Or.inl (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK2_e9_not_valid (e : ℕ) (he : e % 14 = 9)
    {g β : Fin (2 + 3) → ZMod (2 ^ (2 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 2)
    (hg : ∀ i, g i = ((rliftParentE 2 e i : ℕ) :
        ZMod (2 ^ (2 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 14
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 2 e 9 (e / 14)
    (by rw [show (2 * (2 ^ (2 + 1) - 1) : ℕ) = 14 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, -1, -1, 4, -1] : Fin (2 + 3) → ℤ)
    (![1, 1, -1, 0, -1] : Fin (2 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (2 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK2_e10_not_valid (e : ℕ) (he : e % 14 = 10)
    {g β : Fin (2 + 3) → ZMod (2 ^ (2 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 2)
    (hg : ∀ i, g i = ((rliftParentE 2 e i : ℕ) :
        ZMod (2 ^ (2 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 14
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 2 e 10 (e / 14)
    (by rw [show (2 * (2 ^ (2 + 1) - 1) : ℕ) = 14 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_triple_contra hβ' hg' hv
    (![-1, 0, -1, 0, 2] : Fin (2 + 3) → ℤ)
    (![-1, 0, 1, 1, -1] : Fin (2 + 3) → ℤ)
    (![2, 0, 0, -1, -1] : Fin (2 + 3) → ℤ)
    (by decide) (by decide) (by decide)
    (by decide) (by decide) (by decide)
    (j₁ := (⟨0, by decide⟩ : Fin (2 + 3)))
    (j₂ := (⟨0, by decide⟩ : Fin (2 + 3)))
    (j₃ := (⟨0, by decide⟩ : Fin (2 + 3)))
    (by decide) (by decide) (by decide)
    (by decide)
    ⟨1, by decide⟩ ⟨0, by decide⟩ ⟨-1, by decide⟩
    ⟨0, by decide⟩

set_option maxHeartbeats 1600000 in
theorem rliftSmallK2_e11_not_valid (e : ℕ) (he : e % 14 = 11)
    {g β : Fin (2 + 3) → ZMod (2 ^ (2 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 2)
    (hg : ∀ i, g i = ((rliftParentE 2 e i : ℕ) :
        ZMod (2 ^ (2 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 14
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 2 e 11 (e / 14)
    (by rw [show (2 * (2 ^ (2 + 1) - 1) : ℕ) = 14 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, -1, 0, 3, -1] : Fin (2 + 3) → ℤ)
    (![1, 1, 0, -1, -1] : Fin (2 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (2 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK2_e12_not_valid (e : ℕ) (he : e % 14 = 12)
    {g β : Fin (2 + 3) → ZMod (2 ^ (2 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 2)
    (hg : ∀ i, g i = ((rliftParentE 2 e i : ℕ) :
        ZMod (2 ^ (2 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 14
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 2 e 12 (e / 14)
    (by rw [show (2 * (2 ^ (2 + 1) - 1) : ℕ) = 14 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_triple_contra hβ' hg' hv
    (![-1, 0, 1, -1, 1] : Fin (2 + 3) → ℤ)
    (![-1, 0, 2, 0, -1] : Fin (2 + 3) → ℤ)
    (![0, 0, -1, -1, 2] : Fin (2 + 3) → ℤ)
    (by decide) (by decide) (by decide)
    (by decide) (by decide) (by decide)
    (j₁ := (⟨0, by decide⟩ : Fin (2 + 3)))
    (j₂ := (⟨0, by decide⟩ : Fin (2 + 3)))
    (j₃ := (⟨2, by decide⟩ : Fin (2 + 3)))
    (by decide) (by decide) (by decide)
    (by decide)
    ⟨1, by decide⟩ ⟨0, by decide⟩ ⟨1, by decide⟩
    ⟨1, by decide⟩

set_option maxHeartbeats 1600000 in
theorem rliftSmallK2_e13_not_valid (e : ℕ) (he : e % 14 = 13)
    {g β : Fin (2 + 3) → ZMod (2 ^ (2 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 2)
    (hg : ∀ i, g i = ((rliftParentE 2 e i : ℕ) :
        ZMod (2 ^ (2 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 14
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 2 e 13 (e / 14)
    (by rw [show (2 * (2 ^ (2 + 1) - 1) : ℕ) = 14 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, -1, 1, 2, -1] : Fin (2 + 3) → ℤ)
    (![-1, -1, -1, 2, 1] : Fin (2 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (2 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inl (by decide))

set_option maxHeartbeats 1600000 in
/-- Every extra is excluded at `L = 2` (k = 4). -/
theorem rliftSmallK2_not_valid_all (e : ℕ)
    {g β : Fin (2 + 3) → ZMod (2 ^ (2 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 2)
    (hg : ∀ i, g i = ((rliftParentE 2 e i : ℕ) :
        ZMod (2 ^ (2 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hlt : e % 14 < 14 := Nat.mod_lt _ (by norm_num)
  by_cases hc0_14 : e % 14 < 7
  · by_cases hc0_7 : e % 14 < 3
    · by_cases hc0_3 : e % 14 < 1
      · exact rliftSmallK2_e0_not_valid e (by omega) hβ hg
      · by_cases hc1_3 : e % 14 < 2
        · exact rliftSmallK2_e1_not_valid e (by omega) hβ hg
        · exact rliftSmallK2_e2_not_valid e (by omega) hβ hg
    · by_cases hc3_7 : e % 14 < 5
      · by_cases hc3_5 : e % 14 < 4
        · exact rliftSmallK2_e3_not_valid e (by omega) hβ hg
        · exact rliftSmallK2_e4_not_valid e (by omega) hβ hg
      · by_cases hc5_7 : e % 14 < 6
        · exact rliftSmallK2_e5_not_valid e (by omega) hβ hg
        · exact rliftSmallK2_e6_not_valid e (by omega) hβ hg
  · by_cases hc7_14 : e % 14 < 10
    · by_cases hc7_10 : e % 14 < 8
      · exact rliftSmallK2_e7_not_valid e (by omega) hβ hg
      · by_cases hc8_10 : e % 14 < 9
        · exact rliftSmallK2_e8_not_valid e (by omega) hβ hg
        · exact rliftSmallK2_e9_not_valid e (by omega) hβ hg
    · by_cases hc10_14 : e % 14 < 12
      · by_cases hc10_12 : e % 14 < 11
        · exact rliftSmallK2_e10_not_valid e (by omega) hβ hg
        · exact rliftSmallK2_e11_not_valid e (by omega) hβ hg
      · by_cases hc12_14 : e % 14 < 13
        · exact rliftSmallK2_e12_not_valid e (by omega) hβ hg
        · exact rliftSmallK2_e13_not_valid e (by omega) hβ hg


end MinModulus
