import MinModulus.RLiftDispatch

/-!
# Small-k certificates at L = 4 (k = 6)

Generated by `gen_smallk.py`.
-/

namespace MinModulus

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e0_not_valid (e : ℕ) (he : e % 62 = 0)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 0 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, -1, 3, 1, -1, -1] : Fin (4 + 3) → ℤ)
    (![-1, 2, -1, -1, 3, -1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨1, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e1_not_valid (e : ℕ) (he : e % 62 = 1)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 1 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  have hsh : rliftParentSheet 4 = rliftParentE 4 1 := rfl
  rw [← hsh] at hg'
  exact rliftParentSheet_not_valid (by norm_num) (by decide) hβ' hg'

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e2_not_valid (e : ℕ) (he : e % 62 = 2)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 2 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, -1, -1, 3, -1, 1] : Fin (4 + 3) → ℤ)
    (![-1, 2, -1, -1, -1, 1, 1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e3_not_valid (e : ℕ) (he : e % 62 = 3)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 3 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, -1, 1, 1, -1, 2, -1] : Fin (4 + 3) → ℤ)
    (![-1, -1, -1, -1, 1, 2, 1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨1, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e4_not_valid (e : ℕ) (he : e % 62 = 4)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 4 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 2, 1, -1, 0, 0, -1] : Fin (4 + 3) → ℤ)
    (![3, 0, -1, -1, 0, 0, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e5_not_valid (e : ℕ) (he : e % 62 = 5)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 5 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, -1, 0, 1, 1, 1, -1] : Fin (4 + 3) → ℤ)
    (![-1, -1, 0, -1, -1, 3, 1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨1, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e6_not_valid (e : ℕ) (he : e % 62 = 6)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 6 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, -1, -1, 0, 4, -1] : Fin (4 + 3) → ℤ)
    (![1, 2, -1, -1, 0, 0, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e7_not_valid (e : ℕ) (he : e % 62 = 7)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 7 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, -1, -1, 3, 0, 1, -1] : Fin (4 + 3) → ℤ)
    (![-1, 1, -1, -1, 2, 1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨1, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e8_not_valid (e : ℕ) (he : e % 62 = 8)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 8 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, -1, 5, -1, -1, -1] : Fin (4 + 3) → ℤ)
    (![-1, 2, -1, 1, 1, -1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨1, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e9_not_valid (e : ℕ) (he : e % 62 = 9)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 9 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![1, -1, -1, 0, 1, 1, -1] : Fin (4 + 3) → ℤ)
    (![3, -1, -1, 0, -1, -1, 1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e10_not_valid (e : ℕ) (he : e % 62 = 10)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 10 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, -1, 0, -1, 4, -1] : Fin (4 + 3) → ℤ)
    (![1, 2, -1, 0, -1, 0, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e11_not_valid (e : ℕ) (he : e % 62 = 11)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 11 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, -1, 1, 1, 0, 1, -1] : Fin (4 + 3) → ℤ)
    (![-1, -1, -1, -1, 0, 3, 1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨1, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e12_not_valid (e : ℕ) (he : e % 62 = 12)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 12 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, 1, 3, -1, -1, -1] : Fin (4 + 3) → ℤ)
    (![-1, 2, 1, -1, 1, -1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨1, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e13_not_valid (e : ℕ) (he : e % 62 = 13)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 13 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![1, -1, -1, 1, 0, 1, -1] : Fin (4 + 3) → ℤ)
    (![3, -1, -1, -1, 0, -1, 1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e14_not_valid (e : ℕ) (he : e % 62 = 14)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 14 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, -1, -1, 1, 3, -1] : Fin (4 + 3) → ℤ)
    (![1, 2, -1, -1, 1, -1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e15_not_valid (e : ℕ) (he : e % 62 = 15)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 15 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, -1, -1, 1, 4, -1, -1] : Fin (4 + 3) → ℤ)
    (![-1, 1, -1, 1, 0, 1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨1, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e16_not_valid (e : ℕ) (he : e % 62 = 16)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 16 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, 3, 1, -1, -1, -1] : Fin (4 + 3) → ℤ)
    (![-1, 2, -1, 3, -1, -1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨1, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e17_not_valid (e : ℕ) (he : e % 62 = 17)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 17 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![1, -1, 1, -1, 0, 1, -1] : Fin (4 + 3) → ℤ)
    (![-1, -1, 3, -1, 0, -1, 1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inl (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e18_not_valid (e : ℕ) (he : e % 62 = 18)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 18 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, -1, 0, 0, 3, -1] : Fin (4 + 3) → ℤ)
    (![1, 2, -1, 0, 0, -1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e19_not_valid (e : ℕ) (he : e % 62 = 19)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 19 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, -1, 1, -1, 4, -1, -1] : Fin (4 + 3) → ℤ)
    (![-1, 1, 1, -1, 0, 1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨1, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e20_not_valid (e : ℕ) (he : e % 62 = 20)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 20 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, 5, -1, -1, -1, -1] : Fin (4 + 3) → ℤ)
    (![-1, 2, 1, 1, -1, -1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨1, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e21_not_valid (e : ℕ) (he : e % 62 = 21)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 21 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, -1, -1, -1, 0, 5, -1] : Fin (4 + 3) → ℤ)
    (![1, 1, -1, -1, 0, 1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e22_not_valid (e : ℕ) (he : e % 62 = 22)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 22 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, -1, 1, -1, 3, -1] : Fin (4 + 3) → ℤ)
    (![1, 2, -1, 1, -1, -1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e23_not_valid (e : ℕ) (he : e % 62 = 23)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 23 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, -1, -1, 3, 2, -1, -1] : Fin (4 + 3) → ℤ)
    (![-1, 1, -1, -1, 4, -1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨1, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e24_not_valid (e : ℕ) (he : e % 62 = 24)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 24 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 2, 3, -1, -1, -1, -1] : Fin (4 + 3) → ℤ)
    (![-1, 4, -1, 1, -1, -1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e25_not_valid (e : ℕ) (he : e % 62 = 25)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 25 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![1, -1, 1, -1, 1, 0, -1] : Fin (4 + 3) → ℤ)
    (![-1, -1, 3, -1, -1, 0, 1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inl (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e26_not_valid (e : ℕ) (he : e % 62 = 26)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 26 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, 1, -1, -1, 3, -1] : Fin (4 + 3) → ℤ)
    (![1, 2, 1, -1, -1, -1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e27_not_valid (e : ℕ) (he : e % 62 = 27)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 27 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, -1, 1, 1, 2, -1, -1] : Fin (4 + 3) → ℤ)
    (![1, -1, -1, -1, 2, -1, 1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨1, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e28_not_valid (e : ℕ) (he : e % 62 = 28)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 28 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 4, 1, -1, -1, -1, -1] : Fin (4 + 3) → ℤ)
    (![3, 2, -1, -1, -1, -1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨-1, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e29_not_valid (e : ℕ) (he : e % 62 = 29)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 29 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![1, -1, -1, 1, 2, -1, -1] : Fin (4 + 3) → ℤ)
    (![-1, -1, 1, -1, 2, -1, 1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inl (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e30_not_valid (e : ℕ) (he : e % 62 = 30)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 30 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, -1, -1, 3, 1, -1] : Fin (4 + 3) → ℤ)
    (![-1, 2, -1, -1, -1, 3, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e31_not_valid (e : ℕ) (he : e % 62 = 31)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 31 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, -1, -1, 5, 0, -1, -1] : Fin (4 + 3) → ℤ)
    (![-1, 1, -1, 1, 2, -1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨1, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e32_not_valid (e : ℕ) (he : e % 62 = 32)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 32 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 4, -1, -1, -1, -1, 1] : Fin (4 + 3) → ℤ)
    (![-1, 2, -1, -1, -1, -1, 3] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨-1, by decide⟩ (Or.inl (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e33_not_valid (e : ℕ) (he : e % 62 = 33)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 33 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![1, -1, 1, -1, 2, -1, -1] : Fin (4 + 3) → ℤ)
    (![-1, -1, -1, 1, 2, -1, 1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inl (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e34_not_valid (e : ℕ) (he : e % 62 = 34)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 34 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, -1, -1, -1, 3, 1] : Fin (4 + 3) → ℤ)
    (![1, 2, -1, -1, -1, -1, 1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e35_not_valid (e : ℕ) (he : e % 62 = 35)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 35 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, -1, 1, 3, 0, -1, -1] : Fin (4 + 3) → ℤ)
    (![-1, 1, 1, -1, 2, -1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨1, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e36_not_valid (e : ℕ) (he : e % 62 = 36)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 36 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 2, 1, -1, -1, -1, 1] : Fin (4 + 3) → ℤ)
    (![3, 0, -1, -1, -1, -1, 1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e37_not_valid (e : ℕ) (he : e % 62 = 37)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 37 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, -1, -1, -1, 2, 3, -1] : Fin (4 + 3) → ℤ)
    (![1, 1, -1, -1, 2, -1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e38_not_valid (e : ℕ) (he : e % 62 = 38)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 38 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, -1, -1, 4, 0, -1] : Fin (4 + 3) → ℤ)
    (![-1, 2, -1, -1, 0, 2, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e39_not_valid (e : ℕ) (he : e % 62 = 39)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 39 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, -1, 3, 1, 0, -1, -1] : Fin (4 + 3) → ℤ)
    (![-1, 1, -1, 3, 0, -1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨1, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e40_not_valid (e : ℕ) (he : e % 62 = 40)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 40 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, 3, -1, -1, -1, 1] : Fin (4 + 3) → ℤ)
    (![-1, 2, -1, 1, -1, -1, 1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨1, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e41_not_valid (e : ℕ) (he : e % 62 = 41)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 41 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![1, -1, 1, 1, 0, -1, -1] : Fin (4 + 3) → ℤ)
    (![-1, -1, -1, -1, 4, -1, 1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inl (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e42_not_valid (e : ℕ) (he : e % 62 = 42)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 42 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, -1, 0, 3, 0, -1] : Fin (4 + 3) → ℤ)
    (![-1, 2, -1, 0, -1, 2, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e43_not_valid (e : ℕ) (he : e % 62 = 43)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 43 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, -1, 5, -1, 0, -1, -1] : Fin (4 + 3) → ℤ)
    (![-1, 1, 1, 1, 0, -1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨1, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e44_not_valid (e : ℕ) (he : e % 62 = 44)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 44 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, 0, -1, 3, 0, -1] : Fin (4 + 3) → ℤ)
    (![-1, 2, 0, -1, -1, 2, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e45_not_valid (e : ℕ) (he : e % 62 = 45)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 45 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, -1, -1, 1, 0, 3, -1] : Fin (4 + 3) → ℤ)
    (![1, 1, -1, 1, 0, -1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e46_not_valid (e : ℕ) (he : e % 62 = 46)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 46 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, -1, -1, 5, -1, -1] : Fin (4 + 3) → ℤ)
    (![-1, 2, -1, -1, 1, 1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e47_not_valid (e : ℕ) (he : e % 62 = 47)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 47 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 1, 3, -1, 0, -1, -1] : Fin (4 + 3) → ℤ)
    (![-1, 3, -1, 1, 0, -1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e48_not_valid (e : ℕ) (he : e % 62 = 48)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 48 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, -1, 3, -1, -1, 1] : Fin (4 + 3) → ℤ)
    (![-1, 2, -1, -1, 1, -1, 1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨1, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e49_not_valid (e : ℕ) (he : e % 62 = 49)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 49 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, -1, 1, -1, 0, 3, -1] : Fin (4 + 3) → ℤ)
    (![1, 1, 1, -1, 0, -1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e50_not_valid (e : ℕ) (he : e % 62 = 50)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 50 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, -1, 0, 4, -1, -1] : Fin (4 + 3) → ℤ)
    (![-1, 2, -1, 0, 0, 1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e51_not_valid (e : ℕ) (he : e % 62 = 51)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 51 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 3, 1, -1, 0, -1, -1] : Fin (4 + 3) → ℤ)
    (![3, 1, -1, -1, 0, -1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨-1, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e52_not_valid (e : ℕ) (he : e % 62 = 52)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 52 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, 0, -1, 4, -1, -1] : Fin (4 + 3) → ℤ)
    (![-1, 2, 0, -1, 0, 1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e53_not_valid (e : ℕ) (he : e % 62 = 53)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 53 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, -1, -1, -1, 4, 1, -1] : Fin (4 + 3) → ℤ)
    (![-1, 1, -1, -1, 0, 3, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e54_not_valid (e : ℕ) (he : e % 62 = 54)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 54 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, -1, 1, 3, -1, -1] : Fin (4 + 3) → ℤ)
    (![-1, 2, -1, 1, -1, 1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e55_not_valid (e : ℕ) (he : e % 62 = 55)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 55 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 3, 1, 0, -1, -1, -1] : Fin (4 + 3) → ℤ)
    (![3, 1, -1, 0, -1, -1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨-1, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e56_not_valid (e : ℕ) (he : e % 62 = 56)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 56 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, 0, 0, 3, -1, -1] : Fin (4 + 3) → ℤ)
    (![-1, 2, 0, 0, -1, 1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e57_not_valid (e : ℕ) (he : e % 62 = 57)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 57 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, -1, 1, -1, 1, 2, -1] : Fin (4 + 3) → ℤ)
    (![-1, -1, -1, 1, -1, 2, 1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inl (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e58_not_valid (e : ℕ) (he : e % 62 = 58)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 58 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, 1, -1, 3, -1, -1] : Fin (4 + 3) → ℤ)
    (![-1, 2, 1, -1, -1, 1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e59_not_valid (e : ℕ) (he : e % 62 = 59)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 59 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, -1, 0, -1, 3, 1, -1] : Fin (4 + 3) → ℤ)
    (![-1, 1, 0, -1, -1, 3, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e60_not_valid (e : ℕ) (he : e % 62 = 60)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 60 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, 0, -1, -1, -1, 5, -1] : Fin (4 + 3) → ℤ)
    (![1, 2, -1, -1, -1, 1, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨-1, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
theorem rliftSmallK4_e61_not_valid (e : ℕ) (he : e % 62 = 61)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hda := Nat.div_add_mod e 62
  rw [he] at hda
  obtain ⟨β', hβ', hg'⟩ := retarget 4 e 61 (e / 62)
    (by rw [show (2 * (2 ^ (4 + 1) - 1) : ℕ) = 62 from by norm_num]; omega)
    hβ hg
  intro hv
  exact master_pair_contra hβ' hg' hv
    (![-1, -1, -1, -1, 5, 0, -1] : Fin (4 + 3) → ℤ)
    (![-1, 1, -1, -1, 1, 2, -1] : Fin (4 + 3) → ℤ)
    (by decide) (by decide) (by decide) (by decide)
    (j₀ := (⟨0, by decide⟩ : Fin (4 + 3))) (by decide) (by decide)
    (by decide)
    ⟨0, by decide⟩ (Or.inr (by decide))

set_option maxHeartbeats 1600000 in
/-- Every extra is excluded at `L = 4` (k = 6). -/
theorem rliftSmallK4_not_valid_all (e : ℕ)
    {g β : Fin (4 + 3) → ZMod (2 ^ (4 + 3) - 4)}
    (hβ : ∀ i, β i = 0 ∨ β i = sheet 4)
    (hg : ∀ i, g i = ((rliftParentE 4 e i : ℕ) :
        ZMod (2 ^ (4 + 3) - 4)) + β i) :
    ¬ ValidTuple g := by
  have hlt : e % 62 < 62 := Nat.mod_lt _ (by norm_num)
  by_cases hc0_62 : e % 62 < 31
  · by_cases hc0_31 : e % 62 < 15
    · by_cases hc0_15 : e % 62 < 7
      · by_cases hc0_7 : e % 62 < 3
        · by_cases hc0_3 : e % 62 < 1
          · exact rliftSmallK4_e0_not_valid e (by omega) hβ hg
          · by_cases hc1_3 : e % 62 < 2
            · exact rliftSmallK4_e1_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e2_not_valid e (by omega) hβ hg
        · by_cases hc3_7 : e % 62 < 5
          · by_cases hc3_5 : e % 62 < 4
            · exact rliftSmallK4_e3_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e4_not_valid e (by omega) hβ hg
          · by_cases hc5_7 : e % 62 < 6
            · exact rliftSmallK4_e5_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e6_not_valid e (by omega) hβ hg
      · by_cases hc7_15 : e % 62 < 11
        · by_cases hc7_11 : e % 62 < 9
          · by_cases hc7_9 : e % 62 < 8
            · exact rliftSmallK4_e7_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e8_not_valid e (by omega) hβ hg
          · by_cases hc9_11 : e % 62 < 10
            · exact rliftSmallK4_e9_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e10_not_valid e (by omega) hβ hg
        · by_cases hc11_15 : e % 62 < 13
          · by_cases hc11_13 : e % 62 < 12
            · exact rliftSmallK4_e11_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e12_not_valid e (by omega) hβ hg
          · by_cases hc13_15 : e % 62 < 14
            · exact rliftSmallK4_e13_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e14_not_valid e (by omega) hβ hg
    · by_cases hc15_31 : e % 62 < 23
      · by_cases hc15_23 : e % 62 < 19
        · by_cases hc15_19 : e % 62 < 17
          · by_cases hc15_17 : e % 62 < 16
            · exact rliftSmallK4_e15_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e16_not_valid e (by omega) hβ hg
          · by_cases hc17_19 : e % 62 < 18
            · exact rliftSmallK4_e17_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e18_not_valid e (by omega) hβ hg
        · by_cases hc19_23 : e % 62 < 21
          · by_cases hc19_21 : e % 62 < 20
            · exact rliftSmallK4_e19_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e20_not_valid e (by omega) hβ hg
          · by_cases hc21_23 : e % 62 < 22
            · exact rliftSmallK4_e21_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e22_not_valid e (by omega) hβ hg
      · by_cases hc23_31 : e % 62 < 27
        · by_cases hc23_27 : e % 62 < 25
          · by_cases hc23_25 : e % 62 < 24
            · exact rliftSmallK4_e23_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e24_not_valid e (by omega) hβ hg
          · by_cases hc25_27 : e % 62 < 26
            · exact rliftSmallK4_e25_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e26_not_valid e (by omega) hβ hg
        · by_cases hc27_31 : e % 62 < 29
          · by_cases hc27_29 : e % 62 < 28
            · exact rliftSmallK4_e27_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e28_not_valid e (by omega) hβ hg
          · by_cases hc29_31 : e % 62 < 30
            · exact rliftSmallK4_e29_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e30_not_valid e (by omega) hβ hg
  · by_cases hc31_62 : e % 62 < 46
    · by_cases hc31_46 : e % 62 < 38
      · by_cases hc31_38 : e % 62 < 34
        · by_cases hc31_34 : e % 62 < 32
          · exact rliftSmallK4_e31_not_valid e (by omega) hβ hg
          · by_cases hc32_34 : e % 62 < 33
            · exact rliftSmallK4_e32_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e33_not_valid e (by omega) hβ hg
        · by_cases hc34_38 : e % 62 < 36
          · by_cases hc34_36 : e % 62 < 35
            · exact rliftSmallK4_e34_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e35_not_valid e (by omega) hβ hg
          · by_cases hc36_38 : e % 62 < 37
            · exact rliftSmallK4_e36_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e37_not_valid e (by omega) hβ hg
      · by_cases hc38_46 : e % 62 < 42
        · by_cases hc38_42 : e % 62 < 40
          · by_cases hc38_40 : e % 62 < 39
            · exact rliftSmallK4_e38_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e39_not_valid e (by omega) hβ hg
          · by_cases hc40_42 : e % 62 < 41
            · exact rliftSmallK4_e40_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e41_not_valid e (by omega) hβ hg
        · by_cases hc42_46 : e % 62 < 44
          · by_cases hc42_44 : e % 62 < 43
            · exact rliftSmallK4_e42_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e43_not_valid e (by omega) hβ hg
          · by_cases hc44_46 : e % 62 < 45
            · exact rliftSmallK4_e44_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e45_not_valid e (by omega) hβ hg
    · by_cases hc46_62 : e % 62 < 54
      · by_cases hc46_54 : e % 62 < 50
        · by_cases hc46_50 : e % 62 < 48
          · by_cases hc46_48 : e % 62 < 47
            · exact rliftSmallK4_e46_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e47_not_valid e (by omega) hβ hg
          · by_cases hc48_50 : e % 62 < 49
            · exact rliftSmallK4_e48_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e49_not_valid e (by omega) hβ hg
        · by_cases hc50_54 : e % 62 < 52
          · by_cases hc50_52 : e % 62 < 51
            · exact rliftSmallK4_e50_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e51_not_valid e (by omega) hβ hg
          · by_cases hc52_54 : e % 62 < 53
            · exact rliftSmallK4_e52_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e53_not_valid e (by omega) hβ hg
      · by_cases hc54_62 : e % 62 < 58
        · by_cases hc54_58 : e % 62 < 56
          · by_cases hc54_56 : e % 62 < 55
            · exact rliftSmallK4_e54_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e55_not_valid e (by omega) hβ hg
          · by_cases hc56_58 : e % 62 < 57
            · exact rliftSmallK4_e56_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e57_not_valid e (by omega) hβ hg
        · by_cases hc58_62 : e % 62 < 60
          · by_cases hc58_60 : e % 62 < 59
            · exact rliftSmallK4_e58_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e59_not_valid e (by omega) hβ hg
          · by_cases hc60_62 : e % 62 < 61
            · exact rliftSmallK4_e60_not_valid e (by omega) hβ hg
            · exact rliftSmallK4_e61_not_valid e (by omega) hβ hg


end MinModulus
